config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get "/messages/:id" => "pages#home", as: :message

  get "/my_name_is" => "pages#hello", as: :hello
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/pages/hello.html.erb
<h1>Pics du Caine</h1>
<div class="row">
  <div class="col-xs-4">

    <%= image_tag "caine1.jpg", class: "caine1 img-responsive"%>
    <%= image_tag "caine3.jpg", class: "caine3 img-responsive"%>

  </div>
</div>

app/views/pages/home.html.erb
<h1>Caine!</h1>
<p> It's not the size mate, it's how you use it. Your were only supposed to blow the bloody doors off. You know, your bobby dangler, giggle stick, your general-two-colonels, master of ceremonies... Yeah, don't be shy, let's have a look. Your were only supposed to blow the bloody doors off. You wouldn't hit a man with no trousers on, would you? Pull my finger! You are as precious to me as you were to your own mother and father. I swore to them that I would protect you, and I haven't. You wouldn't hit a man with no trousers on, would you? Yes, I used a machine gun. When I get back, remind to tell you about the time I took 100 nuns to Nairobi! It's not the size mate, it's how you use it. When I get back, remind to tell you about the time I took 100 nuns to Nairobi! ,</p>

<p> Pull my finger! It's not the size mate, it's how you use it. My lord! You're a tripod. I want to shoot the pigeons... off my roof. I took a Viagra, got stuck in me throat, I've had a stiff neck for hours. Your were only supposed to blow the bloody doors off. You are as precious to me as you were to your own mother and father. I swore to them that I would protect you, and I haven't. When I get back, remind to tell you about the time I took 100 nuns to Nairobi! My lord! You're a tripod. I want to shoot the pigeons... off my roof. I took a Viagra, got stuck in me throat, I've had a stiff neck for hours. At this point, I'd set you up with a chimpanzee if it'd brought you back to the world! ,</p>

<p> I want to shoot the pigeons... off my roof. At this point, I'd set you up with a chimpanzee if it'd brought you back to the world! You know, your bobby dangler, giggle stick, your general-two-colonels, master of ceremonies... Yeah, don't be shy, let's have a look. You are as precious to me as you were to your own mother and father. I swore to them that I would protect you, and I haven't. My lord! You're a tripod. Jasper: Your baby is the miracle the whole world has been waiting for. You know, your bobby dangler, giggle stick, your general-two-colonels, master of ceremonies... Yeah, don't be shy, let's have a look. Pull my finger! You're only supposed to blow the bloody doors off! You wouldn't hit a man with no trousers on, would you? I took a Viagra, got stuck in me throat, I've had a stiff neck for hours. You're only supposed to blow the bloody doors off! </p>

<p><%= link_to "My Name Is", hello_path %></p>
<div class="row">
  <div class="col-xs-4">

    <%= image_tag "caine2.jpg", class: "caine2 img-responsive"%>
  </div>
</div>